name: Sync GitHub test cases to Jira

on:
  push:
    branches:
      - main
    paths:
      - 'test-cases/**'
      - 'tools/import/sync_to_jira.py'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install pyyaml requests

      - name: Sync to Jira
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          ADD_REMOTE_LINKS: 'true'   # set to 'true' if you also want web links
        run: python tools/import/sync_to_jira.py
