name: Sync Test Cases to Jira

on:
  push:
    branches:
      - main   # or your branch name
  workflow_dispatch: # allows manual trigger

jobs:
  sync-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pandas openpyxl

      - name: Convert Excel → Markdown
        run: python tools/import/excel_to_md.py

      - name: Sync Test Cases to Jira
        run: python tools/import/sync_to_jira.py
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: "SCRUM"   # change to your project key
